// Memory stories for the N5 kanji, written for this app. Each is one picture to hold in mind, built from the shape or
// its parts (see parts.json); shown with the parts on kanji intros, Review cards and Lookup.
// ponytail: N5 only; N4 and N3 kanji show just their parts. Add stories here the same way.
export const KANJI_STORIES: Record<string, string> = {
  日: 'A window with the sun shining through it: one bar across the middle of the sun.',
  一: 'One finger held out flat.',
  国: 'A jewel 玉 kept safe inside a border 囗: a country guards its treasure.',
  人: 'Two legs walking: a person seen from the side.',
  年: 'A farmer bending over the harvest, which comes round once a year.',
  大: 'A person 人 stretching their arms out wide: “this big!”',
  十: 'A cross: ten fingers, both hands crossed.',
  二: 'Two fingers held flat, one above the other.',
  本: 'A tree 木 with a line marking its root, the origin of everything; also a book made from that tree.',
  中: 'An arrow shot right through the middle of a box.',
  長: 'An old man with long hair flowing down to his feet.',
  出: 'Two mountains 山 stacked on top of each other: climb out of the valley to exit.',
  三: 'Three fingers held flat.',
  時: 'The sun 日 moves across the earth 土 an inch 寸 at a time: that is how we tell time.',
  行: 'A crossroads: go left, go right, keep going.',
  見: 'An eye 目 on legs 儿: walk over and see.',
  月: 'A crescent moon with two clouds across it; a month is one moon.',
  後: 'Taking small steps 彳, dragging a thread 幺 and going slowly 夂: you end up behind.',
  前: 'Two horns 八 on top, meat ⺼ and a knife 刂: the butcher stands in front of you.',
  生: 'A sprout pushing up through the ground: life, being born.',
  五: 'A spool of thread wound between two bars: five turns.',
  間: 'Sunlight 日 shining through a gap in the gate 門: the space between.',
  上: 'A line on the ground with a mark pointing up.',
  東: 'The sun 日 rising behind a tree 木: that is east.',
  四: 'A box 囗 with two legs 儿 inside: four corners, four walls.',
  今: 'Under a roof 人, one 一 moment: right now.',
  金: 'Gold nuggets (the two dots) buried in the earth 土 under a roof.',
  九: 'An arm bent at the elbow, almost a fist: nine fingers folded, one left.',
  入: 'Like 人 but leaning in: a person stepping inside.',
  学: 'A child 子 under a roof 冖 with sparks ⺍ flying above: ideas firing while studying.',
  高: 'A tall tower: a roof 亠, a window 口, and another storey 冂口 below.',
  円: 'A round coin standing in its frame: yen.',
  子: 'A baby wrapped up, arms out: a child.',
  外: 'In the evening 夕 the fortune-teller 卜 sits outside.',
  八: 'Two lines spreading apart, like a fan: eight.',
  六: 'A lid 亠 over two legs 八: a six-legged insect under its shell.',
  下: 'A line with a mark hanging below it.',
  来: 'A tree 木 with fruit: next season the fruit will come again.',
  気: 'Steam 气 rising from a pot: energy, spirit, the air around you.',
  小: 'A small thing (the hook) with two crumbs on either side.',
  七: 'An upside-down 7 with a line through it.',
  山: 'Three peaks: a mountain.',
  話: 'Words 言 coming off the tongue 舌: talking.',
  女: 'A woman kneeling with her arms crossed.',
  北: 'Two people sitting back to back, facing away from the cold north wind.',
  午: 'A sundial pole at its shortest shadow: noon.',
  百: 'One 一 above white 白: a hundred white hairs.',
  書: 'A brush 聿 above the day 日: writing in the daytime.',
  先: 'A person on legs 儿 running ahead with a sprout on their head: first, ahead.',
  名: 'In the evening 夕 you can’t see faces, so you call out with your mouth 口: your name.',
  川: 'Three lines of flowing water: a river.',
  千: 'A ten 十 with a slash on top: a thousand.',
  水: 'A stream with splashes flying left and right: water.',
  半: 'A cow 牛 cut down the middle: half.',
  男: 'Power 力 in the rice field 田: the man who ploughs it.',
  西: 'A wine jar under a lid: the sun sets into it in the west.',
  電: 'Rain 雨 above a field with a lightning tail: electricity.',
  校: 'Under a tree 木, people mingle 交 to learn: school.',
  語: 'Saying 言 what I 吾 think: words, language.',
  土: 'A sprout coming out of the soil, a line of ground below.',
  木: 'A tree: trunk, branches, roots.',
  聞: 'An ear 耳 pressed against the gate 門: listening.',
  食: 'A roof over a good 良 meal: eat.',
  車: 'A cart seen from above: the box and the axle with two wheels.',
  何: 'A person 亻 at a street 丁 corner with an open mouth 口: “what?”',
  南: 'Ten 十 over a frame with a cross inside: a warm house facing south.',
  万: 'One 一 over a hook: ten thousand.',
  毎: 'A mother 母 with a hat on: she does it every day.',
  白: 'A ray of light 丿 above the sun 日: white.',
  天: 'A big person 大 with one more line above: the sky above everyone.',
  母: 'A woman with two dots (breasts): mother.',
  火: 'Flames with sparks flying out at both sides: fire.',
  右: 'A hand reaching to the mouth 口: most people eat with the right hand.',
  読: 'Saying 言 the words out loud to sell 売 a story: reading.',
  友: 'Two hands 又 joined together: a friend.',
  左: 'A hand holding a tool 工: the left hand steadies it.',
  休: 'A person 亻 leaning against a tree 木: taking a rest.',
  父: 'Two crossed tools 乂 under two strokes: father’s work.',
  雨: 'Raindrops falling under the sky’s roof.',
}
